### ISSUE TITLE
Collaborative blog post

### ISSUE THREAD

**Issue by trallard** [pycon-mentored-sprints/organisational#12]
Collaborative blog post! I have created a barebones doc [here](https://github.com/pycon-mentored-sprints/write_ups/blob/master/RealPython_post.md).  In about the organizers please fill in with your own information.

Suggested by Nina

> About us, how many years we've been programming Python, how we discovered it, our favorite language feature, why we're volunteering our time for the sprints, and what we hope participants will get out of it. 

If you are also comfortable sending a picture, please do.

If there is something you'd like to add about the sprints also feel free to add to the introduction or wrap up section.

**Comment by nnja** [comment]
@trallard Do you think this might be better suited for a google doc that we can all edit at the same time?

**Comment by trallard** [comment]
You might be right. Will create and start today
