### ISSUE TITLE
Create submission forms

### ISSUE THREAD

**Issue by trallard** [pycon-mentored-sprints/organisational#2]
Need to have the submission forms ready  for :
- [x] Attendees
- [x] OSS projects and mentors

**Comment by Mariatta** [comment]
I've started this form for project sign up. Feedback appreciated:
https://docs.google.com/forms/d/e/1FAIpQLSd3D0BvnhgLRbtK2LOC-aAAkvZt484RCpwY0lpFdsFljEy9ig/viewform?usp=sf_link
