### ISSUE TITLE
[ASSETS] Create sprints image / social assets

### ISSUE THREAD

**Issue by trallard** [pycon-mentored-sprints/organisational#23]
@trallard will create a series of graphical assets for the mentored sprints, which include:
- social media card (for Twitter, Slack, instagram use)
- banner: with main details for the event so this can be pinned in multiple places (.e.g 2020 website)

Once completed will be stored in a "digital-assets" repo

﻿

**Comment by trallard** [comment]
Hi all 

I have worked on the following assets:

1.
![Asset 2](https://user-images.githubusercontent.com/23552331/74965420-20cf8380-540d-11ea-8364-d5232d1126b1.png)
2.
![Asset 3](https://user-images.githubusercontent.com/23552331/74965422-2200b080-540d-11ea-9217-2706ce2c82dc.png)
3.
![Asset 8](https://user-images.githubusercontent.com/23552331/74965431-23ca7400-540d-11ea-985c-ce324d494be6.png)
4.
![Asset 4](https://user-images.githubusercontent.com/23552331/74965425-22994700-540d-11ea-99fc-f2f404cacd6c.png)
5.
![Asset 5](https://user-images.githubusercontent.com/23552331/74965426-22994700-540d-11ea-8fcb-381243f5d646.png)
6.
![Asset 6](https://user-images.githubusercontent.com/23552331/74965429-2331dd80-540d-11ea-8edb-cf80855ff1bf.png)
7.
![Asset 7](https://user-images.githubusercontent.com/23552331/74965430-23ca7400-540d-11ea-91bd-1cab4daaa112.png)

Typography only:
![Asset 9](https://user-images.githubusercontent.com/23552331/74965432-24630a80-540d-11ea-9844-bf3cfcfff039.png)

**Comment by trallard** [comment]
Can you please comment on your favourites? We could use the hex one to print some nice stickers for the day or another type of swag (token?) for the attendees on the day.


@nnja @Cheukting @katialira @valerybriz

**Comment by Cheukting** [comment]
I like number 3 and 6. The hexagon one for stickers 👍🏻The typography one is good as well (maybe we can make a pin)

**Comment by nnja** [comment]
I like #3 

Maybe a variant of #6 with a bigger font size?

I love the hex sticker, but I think the font could also be a little bigger or possibly more bold. I'm worried the printed version might be hard to read

**Comment by trallard** [comment]
Gotcha will play with font sizes tomorrow and add the variants here

**Comment by trallard** [comment]
Ok so I have modified the most popular ones, mostly to make the fonts bigger and played a bit with the spacing around the letters to allow for readability.

I also changed a bit the shape of the snake in one of the designs to make it nicer looking. Let me know what you think


<img width="229" alt="Asset 13@2x" src="https://user-images.githubusercontent.com/23552331/75036691-5fffe200-54aa-11ea-8a6a-56badb953282.png">

![Asset 16](https://user-images.githubusercontent.com/23552331/75040111-fa175880-54b1-11ea-8480-45ba0cd75ee0.png)

![Asset 15](https://user-images.githubusercontent.com/23552331/75036704-6a21e080-54aa-11ea-9d29-bc9f2b92aa20.png)

**Comment by trallard** [comment]
Also, I just noticed one of the designs' colour was off so I corrected it 

![Asset 16](https://user-images.githubusercontent.com/23552331/75036835-a9503180-54aa-11ea-9a7b-276f8cfd3ec9.png)

**Comment by trallard** [comment]
I also created a "flyer" that we can use for twitter and other outreach stuff

![Mentored sprints banner](https://user-images.githubusercontent.com/23552331/75042016-a7d83680-54b5-11ea-96ab-b4b0e3bae85d.png)

And a Twitter banner

![Twitter banner](https://user-images.githubusercontent.com/23552331/75050323-aada2380-54c3-11ea-841b-5f5f22e263ce.png)

**Comment by valerybriz** [comment]
Awesome!! Loved the snakes and colors!

**Comment by nnja** [comment]
Love love love the new sticker designs. They look awesome.

For the flyer, it would be nice to up the contrast of the white letters in the pink circle and the purple text on the dark but background for accessibility. They're a bit hard to read.

**Comment by trallard** [comment]
Changed the banner as per Nina's suggestions. 

I have now created a new repo https://github.com/pycon-mentored-sprints/digital-assets for all digital assets. So far it contains the banners and will add the stickers and other assets tomorrow. Feel free to use the assets as you see fit for outreach
