### ISSUE TITLE
[COMMS] - Do we need a Twitter account?

### ISSUE THREAD

**Issue by trallard** [pycon-mentored-sprints/organisational#24]
The mentored sprints are likely to become part of PyCon US on a rolling  basis after discussions with PyCon staff. 

Do we think it would be a good idea to create a Twitter account for all events related (i.e running at other conferences or the such)﻿

**Comment by Cheukting** [comment]
I think it's a good idea to have a twitter account for people who want to follow the further for the next version of the event and so on. It's also good to spread the new when we recruit participants and mentors.

**Comment by trallard** [comment]
Great, I have created a Twitter account for this  https://twitter.com/MentoredSprints

If you'd like to have the ability to Tweet from it please let me know and I'll add you to the team

**Comment by valerybriz** [comment]
I would like to have access so we can start making some noice over twitter with the assets that are already done :)
