### ISSUE TITLE
[COMMS] - Update PyCon US website

### ISSUE THREAD

**Issue by trallard** [pycon-mentored-sprints/organisational#25]
I recently updated the website at [https://us.pycon.org/2020/hatchery/mentoredsprints/](https://us.pycon.org/2020/hatchery/mentoredsprints/). 

The PyCon official announcement about the hatchery programes is due on the 21st of February. Can all please have a look at the website above and make sure you are happy with the info on it? If you need to update your profile you should have access to do it, if not please ping @trallard﻿

**Comment by Cheukting** [comment]
Looks good to me

**Comment by valerybriz** [comment]
Looks good for me too :)
