### ISSUE TITLE
[COMMS] - Draft email to invite mentors from 2019

### ISSUE THREAD

**Issue by trallard** [pycon-mentored-sprints/organisational#26]
Draft a small email that we can send to the previous mentors in case they want to be involved again﻿

**Comment by Cheukting** [comment]
Hi <name>,

Thank you so much for mentoring at PyCon Mentored Sprints in 2019! With your help, it was a great success and everyone was enjoying contributing to open-source.

We are proud to announce that the Mentored Sprints will be coming back this year at PyCon, on 17th April (Friday) at <time TBC> to <time TBC>. We would like to invite you once again to join us. For more information about the sprint, you can visit the PyCon US hatchery program website: https://us.pycon.org/2020/hatchery/mentoredsprints/ 

We would love to see you again!

Best,
PyCon Mentored Sprint Organizing Team
