### ISSUE TITLE
Token / swag 

### ISSUE THREAD

**Issue by trallard** [pycon-mentored-sprints/organisational#27]
Last year Nina printed some stickers and got also some buttons for the mentors. 
It would be great if we could do something similar this year. 

I personally love this:

<https://twitter.com/treyhunner/status/833522617223172101?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E833522617223172101&ref_url=https%3A%2F%2Fopensource.com%2Farticle%2F19%2F5%2Fpycon-developer-sprints>

Do you have any ideas/suggestions?﻿

**Comment by Cheukting** [comment]
The pin looks great! I personally don't prefer too many fancy swag (as I got a lot from conferences) but stickers and pins to show appreciation for participating are good!

**Comment by trallard** [comment]
@nnja  now that the designs are all done shall we try and get a sample of the charms?

https://www.stickermule.com/products/acrylic-charms

I added three simplified designs (in addition to the existing stickers design) which might be more suitable for the charms. Thoughts?

1. ![circle2](https://user-images.githubusercontent.com/23552331/75572648-16d40300-5a53-11ea-92d7-1d37c65e43fa.png)
2. ![circular-logo](https://user-images.githubusercontent.com/23552331/75572656-19cef380-5a53-11ea-9cf1-8966dcc2986f.png)
3. ![text-small-rectangle](https://user-images.githubusercontent.com/23552331/75572659-1a678a00-5a53-11ea-942e-f19c9ea83733.png)


For reference the other logos:

![hex-sticker](https://user-images.githubusercontent.com/23552331/75572694-2c492d00-5a53-11ea-98b5-7d52dfaaad51.png)
![blue-pink-text](https://user-images.githubusercontent.com/23552331/75572714-3408d180-5a53-11ea-858f-d0a4fdb7b42f.png)

**Comment by Cheukting** [comment]
I love the 1st one

**Comment by nnja** [comment]
I like the first one as well.

**Comment by nnja** [comment]
Let's pick our top two designs and preferred size (1"x1" or 2"x2") and I'll order samples. @trallard what is your favorite?

**Comment by trallard** [comment]
I prefer the first one and the third (text only) will leave the hex one for stickers. 

For size maybe 2in so that the details do not get lost. 
All the files are in the assets repo and are in high quality PNG version let me know if you have any problems.

Holographic stickers are on offer at the moment so I can order 50 for 19 USD from stickermule so will go ahead and order the hex ones.

**Comment by nnja** [comment]
I'm going to put ordering on hold, until we get an updated from PyCon on if they will go virtual or postpone.

**Comment by Cheukting** [comment]
Good call. Travel form UK is banned so I am pretty sure I cannot make it.

**Comment by trallard** [comment]
Will decide on online swag: 

- dev.to badge (@trallard  to chase)
- @nnja suggested a photo frame


Other suggestions?
