### ISSUE TITLE
Decide on final schedule

### ISSUE THREAD

**Issue by trallard** [pycon-mentored-sprints/organisational#28]
We are scheduled on the 17th of February but we have not scheduled the exact times yet. 

Since the schedule for the whole thing is not finalised yet <https://us.pycon.org/2020/schedule/> we might have to wait until we know when the breaks are and the such. 

﻿

**Comment by trallard** [comment]
Once we have decided on this we have to notify Jackie and Ewa so they can add it to the PyCon US website

**Comment by Cheukting** [comment]
I have no personal preference for this. Happy to accommodate any arrangements.
