### ISSUE TITLE
2020 website

### ISSUE THREAD

**Issue by trallard** [pycon-mentored-sprints/organisational#29]
Create the main site for the 2020 sprints. 

We have a site for 2019 <https://github.com/pycon-mentored-sprints/2019-pycon-mentored-sprint> we could either update this or create a new one﻿

**Comment by Cheukting** [comment]
Or we can make a branch (or tag) called "2019" then update the master as the latest

**Comment by valerybriz** [comment]
> Or we can make a branch (or tag) called "2019" then update the master as the latest

I think this is a good idea, since it would be needed every year.

**Comment by trallard** [comment]
Closing as I created a PR - can someone check <https://github.com/pycon-mentored-sprints/mentored-sprints-website/pull/6>?
