### ISSUE TITLE
Decide on online schedule

### ISSUE THREAD

**Issue by trallard** [pycon-mentored-sprints/organisational#32]
**When**: 17th May 

We discussed over the last meeting that we would cover multiple timezones:

- Europe: Tania & Cheuk can cover
- Americas (CDT ad reference): Nina, Valery & Katia
- APAC: Zac needs to confirm (otherwise will reach out to other folks from PyCon AU)

Need to finalise the schedule if someone can come up with reasonable times that would be great.

Maybe @Cheukting  or @nnja

**Comment by nnja** [comment]
Did we decide how many hours the event should span?

**Comment by Cheukting** [comment]
Also how long should the whole program be?

**Comment by trallard** [comment]
Hi quick update Zac has agreed to lead the APAC region!! 


I can't remember if we said 4 hours per region (APAC, EMEA, Americas)? To allow for overlap among them 🤔🤔

I am open for suggestions here really. 
I  also don't want anyone to feel like they are spending their whole day off in front of a computer 😬

**Comment by Cheukting** [comment]
I think 4 hours per region is good. If they want more they can join other
regions LOL

**Comment by Cheukting** [comment]
Good new that Zac can lead!
