### ISSUE TITLE
Create Discord server

### ISSUE THREAD

**Issue by trallard** [pycon-mentored-sprints/organisational#36]
Need to create a server. We need to make sure:
- have an organisers channel
- have a mentors channel
- general channel
- one-click use invite link only

Also need to make sure we have good enough moderator capabilities

**Comment by trallard** [comment]
@nnja Made me aware of the Python Discord server. So we were discussing if it would be a good idea to use this for the mentored sprints as this already has a lot of members and a help channel. 

This is open for discussion and we might then need to contact the admins to see if we could piggy-back on this server

**Comment by Cheukting** [comment]
Hey I am in the Python Discord server as well, but I am never active there. 

Reason for not using that is 1. we do not have full admin right to the server 2. It may be a bit overwhelming for people not familiar with Discord to start using that server because it's size and complex structure. 

Reason for using would be 1. if we got support from their admin they can set up everything Discord related for us 2. Publicity 3. support form their community

**Comment by trallard** [comment]
@nnja do you know the admin? If so could we ask them to use the server?

**Comment by trallard** [comment]
I think whatever the decision is we need to move fast and have this created / sorted for when I send the final details to folks. Ideally wanted to notify everyone tomorrow  or Wednesday

**Comment by Cheukting** [comment]
Maybe we should set up a server anyway? I can help with that. Have some
time this evening if @Tania you wanna set up today.

Cheuk

**Comment by nnja** [comment]
@trallard @Cheukting yes, the admins reached out to me about a different topic, so I have a direct line to them. So far they've been incredibly friendly and helpful.

**Comment by nnja** [comment]
the pros/cons:

pros:
- there's additional ways to get help and tons of topic channels
- we'll be funneling participants into an already active community. I imagine activity in our discord will die down in the days/weeks after the event.
- the server and avenues for long-term moderation are already in place. For our own discord, we'll have to think about long term moderation. 

cons:
- It's a big server and might be too much / overwhelming for someone new to discord. 
- This idea is definitely contingent on the mods supporting us and our idea

If we make our own discord we should think a bit about what we plan on doing with it after the event is over. Do we try to keep the space open? If so, are we able to provide resources for long term moderation? Or do we want to shut down the server a week or two after the event to prevent additional administrative burdens?

**Comment by trallard** [comment]
Great to hear @nnja, here are my thoughts:

- I think maintaining a server post mentored sprints would be quite a lot of extra work. I personally cannot commit to long term support on yet another community platform 
- Though the existing server might be daunting it might also be a way to introduce folks to the community and provide them with a platform they can turn to for help during/after the sprints

Any chance you could ask the mods and see if they'd be happy to add us?

**Comment by trallard** [comment]
Done - created Mentored sprints server which will be long-term shared and maintained by Python sprints (@Cheukting ) and scikit-learn sprints
